import { Category, CategoryId, AreaId, CategorySpendingType } from "./types";

export const DEFAULT_CATEGORIES: Record<CategoryId, Category> = {
  [CategoryId.RENT]: {
    name: "Rent",
    matches: ["rent", "Housing Management AG"],
    area: AreaId.HOUSING,
    spendingType: CategorySpendingType.NEED,
    emoji: "🛏️",
  },
  [CategoryId.UTILITIES]: {
    name: "Utilities",
    matches: [
      "mobile",
      "energy",
      "electricity",
      "internet",
      "swisscom",
      "sunrise",
      "salt",
      "ewz",
      "heizung",
      "water",
      "gas",
      "sewage",
      "trash",
      "recycling",
      "green.ch",
    ],
    area: AreaId.HOUSING,
    spendingType: CategorySpendingType.NEED,
    emoji: "💡",
  },
  [CategoryId.HOUSE_INSURANCE]: {
    name: "House Insurance",
    matches: ["house insurance", "hausversicherung"],
    area: AreaId.HOUSING,
    spendingType: CategorySpendingType.NEED,
    emoji: "📝",
  },
  [CategoryId.GROCERIES]: {
    name: "Groceries",
    matches: ["migros", "coop", "aldi", "lidl", "denner", "spar", "carrefour"],
    area: AreaId.FOOD,
    spendingType: CategorySpendingType.NEED,
    emoji: "🍎",
  },
  [CategoryId.EATING_OUT]: {
    name: "Eating Out",
    matches: [
      "restaurant",
      "cafe",
      "coffee",
      "café",
      "Caffé",
      "pizzeria",
      "burger",
      "keller",
      "bistro",
      "bakery",
      "bäckerei",
      "confiseur",
      "confiserie",
      "pane e vino",
      "hong kong food",
      "kennedy",
      "swaad",
      "bachmann",
      "äss-bar",
      "milchbar",
      "yalda",
      "starbucks",
      "mcdonald",
      "subway",
      "kebab",
      "sushi",
      "Bäckerei",
      "Conditorei",
      "Crêpes",
      "creperie",
      "gyros",
    ],
    area: AreaId.FOOD,
    spendingType: CategorySpendingType.WANT,
    emoji: "🍔",
  },
  [CategoryId.HEALTH_INSURANCE]: {
    name: "Health Insurance",
    matches: ["health insurance", "gesundheitsversicherung", "krankenkasse", "kpt"],
    area: AreaId.HEALTH,
    spendingType: CategorySpendingType.NEED,
    emoji: "🏥",
  },
  [CategoryId.MEDICATION]: {
    name: "Medication",
    matches: ["medication", "medicine", "pharmacy", "apotheke"],
    area: AreaId.HEALTH,
    spendingType: CategorySpendingType.NEED,
    emoji: "💊",
  },
  [CategoryId.DOCTORS]: {
    name: "Visits & Procedures",
    matches: ["arzt", "spital", "klinik"],
    area: AreaId.HEALTH,
    spendingType: CategorySpendingType.NEED,
    emoji: "👨‍⚕️",
  },
  [CategoryId.PUBLIC_TRANSPORT]: {
    name: "Public Transport",
    matches: ["verkehrsverbund", "SBB", "CFF", "FFS", "VBZ", "SZU", "TPG Transports"],
    area: AreaId.TRANSPORTATION,
    spendingType: CategorySpendingType.NEED,
    emoji: "🚌",
  },
  [CategoryId.VEHICLE]: {
    name: "Vehicle",
    matches: ["benzin", "fahrzeugversicherung"],
    area: AreaId.TRANSPORTATION,
    spendingType: CategorySpendingType.NEED,
    emoji: "🚗",
  },
  [CategoryId.CLOTHING]: {
    name: "Clothing",
    matches: ["Skechers", "Shoes", "C & A Mode"],
    area: AreaId.SHOPPING,
    spendingType: CategorySpendingType.NEED,
    emoji: "👕",
  },
  [CategoryId.BARBER]: {
    name: "Barber",
    matches: ["barber", "haarschnitt"],
    area: AreaId.SHOPPING,
    spendingType: CategorySpendingType.NEED,
    emoji: "💈",
  },
  [CategoryId.GIFTS]: {
    name: "Gifts",
    matches: ["geschenk"],
    area: AreaId.SHOPPING,
    spendingType: CategorySpendingType.WANT,
    emoji: "🎁",
  },
  [CategoryId.GOING_OUT]: {
    name: "Entertainment",
    matches: ["cinema", "kino", "theater", "ticket"],
    area: AreaId.ENTERTAINMENT,
    spendingType: CategorySpendingType.WANT,
    emoji: "🎬",
  },
  [CategoryId.TRAVEL]: {
    name: "Travel",
    matches: ["hotel", "booking.com", "Iberia"],
    area: AreaId.ENTERTAINMENT,
    spendingType: CategorySpendingType.WANT,
    emoji: "🛫",
  },
  [CategoryId.INVESTMENT]: {
    name: "Investment",
    matches: ["pillar"],
    area: AreaId.INVESTMENT,
    spendingType: CategorySpendingType.SAVING,
    emoji: "💰",
  },
  [CategoryId.UNCATEGORIZED]: {
    name: "Uncategorized",
    matches: [],
    area: AreaId.UNCATEGORIZED,
    emoji: "❓",
  },
};
